### ISSUE TITLE
Apple Silicon run-time error

### ISSUE THREAD

**Issue by buu700** [Level/rocksdb#177] opened 2021-08-14 19:12 UTC
After successfully installing a version of rocksdb with #171 patched in ([buu700/rocksdb-tmp](https://github.com/buu700/rocksdb-tmp)), I ran into the following error on macOS 11.5.1:

```
[ 3:10PM] buu700@Cyph:~$ node
Welcome to Node.js v16.1.0.
Type ".help" for more information.
> require('rocksdb')
dyld: lazy symbol binding failed: Symbol not found: __Z20crc32c_runtime_checkv
  Referenced from: /Users/buu700/node_modules/rocksdb/build/Release/leveldown.node
  Expected in: flat namespace

dyld: Symbol not found: __Z20crc32c_runtime_checkv
  Referenced from: /Users/buu700/node_modules/rocksdb/build/Release/leveldown.node
  Expected in: flat namespace

Abort trap: 6
```

Edit: Looks like https://github.com/facebook/rocksdb/issues/7710 was the issue, in which case simply updating RocksDB should resolve this.

**Comment by vweevers** [comment] 2021-08-14 21:04
Duplicate of https://github.com/Level/rocksdb/issues/169, fixed by https://github.com/Level/rocksdb/pull/171, will be released soon.

**Comment by vweevers** [comment] 2021-08-14 21:05
Sorry, misread that you already tried with #171.

**Comment by vweevers** [comment] 2021-08-14 21:24
> Looks like facebook/rocksdb#7710 was the issue, in which case simply updating RocksDB should resolve this.

We're at v6.17.3, which already has that fix (https://github.com/facebook/rocksdb/commit/ee4bd4780b321ddb5f92a0f4eb956f2a2ebd60dc)

**Comment by buu700** [comment] 2021-08-14 21:26
Ah okay, guess my assumption there was wrong.

**Comment by buu700** [comment] 2021-08-17 18:19
I'm not sure if this is related or needs to be a new ticket, but I'm also getting the following error in an Electron app (same patched version of rocksdb, built with electron-builder on x86 macOS).

<img width="1113" alt="Screen Shot 2021-08-17 at 2 15 45 PM" src="https://user-images.githubusercontent.com/415435/129779267-6039e59c-247a-477e-bc28-13db3e42d1b9.png">

**Comment by nbelie** [comment] 2021-08-20 14:22
Hello there,
Thanks for the info, I was desperately tearing my hair out :) 
Do you know when the patch will be available in this lib ?

**Comment by Nazgolze** [comment] 2021-09-05 21:33
I'm running into the problem that @buu700 described.
I haven't looked too deeply into it yet, but I think it's the lack of https://github.com/facebook/rocksdb/pull/7883 in rocksdb v6.17.3 

Will look into this more this week

**Comment by Nazgolze** [comment] 2021-09-14 15:35
I tried the following:
```
diff --git a/deps/rocksdb/rocksdb.gyp b/deps/rocksdb/rocksdb.gyp
index c5f6663..9c604eb 100644
--- a/deps/rocksdb/rocksdb.gyp
+++ b/deps/rocksdb/rocksdb.gyp
@@ -166,6 +166,7 @@
                   , '-stdlib=libc++'
                   , '-fno-omit-frame-pointer'
                   , '-momit-leaf-frame-pointer'
+                  , '-march=armv8-a+crc+crypto'
                 ]
 # , 'OTHER_LDFLAGS': ['-stdlib=libc++']
                 , 'GCC_ENABLE_CPP_RTTI': 'YES'
```
and it made no difference.

So much for my theory :sweat_smile:

**Comment by Nazgolze** [comment] 2021-09-14 15:48
aaaahh, I didn't add `, 'rocksdb/util/crc32c_arm64.cc'`, I will give this another try

**Closed** 2021-09-28 13:56 UTC
Labels: bug
